language: node_js
node_js:
- "8"
- "9"

install:
- npm -g install npm
- npm install

script:
- npm run build-css
- npm run test
- npm run build

notifications:
    email: false

cache:
    directories:
    - node_modules
