language: node_js
node_js:
  - "8"

# will run `npm install` automatically

script:
  - npm -g install truffle
  - npm run build-css
  - npm run test
  - npm run build

notifications:
    email: false

cache:
  directories:
    - node_modules
