language: node_js
node_js:
- "8"

script:
- npm -g install truffle npm
- npm install
- npm run build-css
- npm run test
- npm run build

notifications:
    email: false

cache:
    directories:
    - node_modules
